-- SAM Phénologie — schéma Supabase v2.6
-- À exécuter une fois dans Supabase > SQL Editor.

create table if not exists public.parcels (
  id text primary key,
  exploitation text not null,
  name text not null,
  variety text not null,
  custom_variety_name text,
  stage_c_date date,
  base_temp double precision not null default 5,
  weather_location_name text not null default 'Marsillargues',
  weather_admin1 text,
  weather_country text default 'France',
  latitude double precision not null default 43.6343,
  longitude double precision not null default 4.1706,
  elevation double precision,
  timezone text default 'Europe/Paris',
  updated_at timestamptz not null default now()
);

-- Mise à niveau d'une table parcels déjà existante.
alter table public.parcels add column if not exists custom_variety_name text;

create table if not exists public.observations (
  id bigint generated by default as identity primary key,
  parcel_id text not null references public.parcels(id) on delete cascade,
  obs_date date not null,
  stage text not null,
  updated_at timestamptz not null default now(),
  unique (parcel_id, obs_date)
);

alter table public.parcels enable row level security;
alter table public.observations enable row level security;

grant select on public.parcels to anon, authenticated;
grant select on public.observations to anon, authenticated;
grant insert, update, delete on public.parcels to authenticated;
grant insert, update, delete on public.observations to authenticated;
grant usage, select on sequence public.observations_id_seq to authenticated;

-- Lecture publique : producteurs / visiteurs peuvent consulter.
drop policy if exists "parcels_public_read" on public.parcels;
create policy "parcels_public_read"
on public.parcels for select
to anon, authenticated
using (true);

drop policy if exists "observations_public_read" on public.observations;
create policy "observations_public_read"
on public.observations for select
to anon, authenticated
using (true);

-- Écriture réservée aux comptes Supabase authentifiés (comptes SudExpé uniquement).
drop policy if exists "parcels_authenticated_insert" on public.parcels;
create policy "parcels_authenticated_insert"
on public.parcels for insert
to authenticated
with check (true);

drop policy if exists "parcels_authenticated_update" on public.parcels;
create policy "parcels_authenticated_update"
on public.parcels for update
to authenticated
using (true)
with check (true);

drop policy if exists "parcels_authenticated_delete" on public.parcels;
create policy "parcels_authenticated_delete"
on public.parcels for delete
to authenticated
using (true);

drop policy if exists "observations_authenticated_insert" on public.observations;
create policy "observations_authenticated_insert"
on public.observations for insert
to authenticated
with check (true);

drop policy if exists "observations_authenticated_update" on public.observations;
create policy "observations_authenticated_update"
on public.observations for update
to authenticated
using (true)
with check (true);

drop policy if exists "observations_authenticated_delete" on public.observations;
create policy "observations_authenticated_delete"
on public.observations for delete
to authenticated
using (true);
